### ISSUE TITLE
Kod gerekenden daha karmaşık ve doğru düzgün çalışmıyor

### ISSUE THREAD

**Issue by lostfxo** [alispw77/kelime-bulmaca-discordJS#1]
Bu kadar json parse vs. ile uğraşmak yerine quick.db tarzı modüller kullanılması çok daha mantıklı değil mi?
Bot çoğu zaman kendi kendine çöküyor, doğru düzgün çalışmıyor. Kod gerekenden daha komplike ve 'ab' tarzı şeyleri kelime olarak sayıyor.

**Comment by alispw77** [comment]
Uzun zaman oldu, json.parse ve dosya okuması yapıyorum zaten gereksiz. Veritabanı sağlayıcım yoktu o yüzden öyle çalışamamıştım. Bir de o zamanlar sadece can sıkıntısından uğraşıyordum pek de tavsiye etmem kullanılmasını daha sağlamını yapmıştım ama buraya koymadım sanırım. Artık uğraşmıyorum da acemi vakitlerimdi. Yorum için teşekkürler
